---

- name: Create logrotate configuration
  ansible.builtin.template:
    src: "etc/logrotate.d/sudo.j2"
    dest: /etc/logrotate.d/sudo
    owner: root
    group: root
    mode: '0644'
  when:
    - (sudo_logfiles | length > 0)
